# Generated by Django 4.2 on 2025-02-12 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_created_by', models.CharField(choices=[('self', 'Self'), ('parent', 'Parent'), ('siblings', 'Siblings'), ('relative', 'Relative'), ('friend', 'Friend')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('height', models.FloatField()),
                ('preferred_height', models.FloatField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('preferred_age', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('preferred_weight', models.FloatField(blank=True, null=True)),
                ('education', models.CharField(max_length=255)),
                ('preferred_education', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('preferred_location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
