# Generated by Django 4.2 on 2025-02-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='join_date',
            field=models.DateField(auto_now=True),
        ),
    ]
