# Generated by Django 4.2 on 2025-02-15 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_registration_join_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='join_date',
            new_name='join',
        ),
    ]
