# Generated by Django 4.2 on 2025-02-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_rename_join_registration_just_join'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='just_join',
            new_name='join_date',
        ),
    ]
