# Generated by Django 4.2 on 2025-02-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_alter_registration_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='join_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
